// <auto-generated />
using System;
using CA_EFHastaneOtomasyon.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA_EFHastaneOtomasyon.Migrations
{
    [DbContext(typeof(EFHastaneOtomasyonContext))]
    partial class EFHastaneOtomasyonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Doktor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DiplomaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoktorAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Doktors");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Hasta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HastaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hastas");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.HastaBilgileri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Boy")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<double?>("Kilo")
                        .HasColumnType("float");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HastaId")
                        .IsUnique();

                    b.ToTable("HastaBilgileris");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Oda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BinaNo")
                        .HasColumnType("int");

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<int>("OdaNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DoktorId")
                        .IsUnique();

                    b.ToTable("Odas");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Odeme", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("HastaId");

                    b.ToTable("Odemes");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Randevu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DoktorID")
                        .HasColumnType("int");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RandevuZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DoktorID");

                    b.HasIndex("HastaId");

                    b.ToTable("Randevus");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.TahlilSonucu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<string>("TahlilDosyaLinki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TahlilZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("HastaId");

                    b.ToTable("TahlilSonucus");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.HastaBilgileri", b =>
                {
                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Hasta", "Hasta")
                        .WithOne("HastaBilgileri")
                        .HasForeignKey("CA_EFHastaneOtomasyon.Models.Entities.HastaBilgileri", "HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Oda", b =>
                {
                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Doktor", "Doktor")
                        .WithOne("Oda")
                        .HasForeignKey("CA_EFHastaneOtomasyon.Models.Entities.Oda", "DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Odeme", b =>
                {
                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Hasta", "Hasta")
                        .WithMany("Odemes")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Randevu", b =>
                {
                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Doktor", null)
                        .WithMany("Randevus")
                        .HasForeignKey("DoktorID");

                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.TahlilSonucu", b =>
                {
                    b.HasOne("CA_EFHastaneOtomasyon.Models.Entities.Hasta", "Hasta")
                        .WithMany("TahlilSonucus")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Doktor", b =>
                {
                    b.Navigation("Oda")
                        .IsRequired();

                    b.Navigation("Randevus");
                });

            modelBuilder.Entity("CA_EFHastaneOtomasyon.Models.Entities.Hasta", b =>
                {
                    b.Navigation("HastaBilgileri")
                        .IsRequired();

                    b.Navigation("Odemes");

                    b.Navigation("TahlilSonucus");
                });
#pragma warning restore 612, 618
        }
    }
}
